version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
    open-pull-requests-limit: 10
    groups:
      bouncycastle-security:
        applies-to: security-updates
        patterns:
          - "org.bouncycastle:*"
      bouncycastle:
        applies-to: version-updates
        patterns:
          - "org.bouncycastle:*"
        update-types:
          - "minor"
          - "patch"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
  - package-ecosystem: "cargo"
    directory: "/rust"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
    groups:
      rustcrypto-stack:
        applies-to: version-updates
        patterns:
          - "aes-gcm"
          - "der"
          - "getrandom"
          - "p256"
          - "pbkdf2"
          - "rsa"
          - "sha2"
          - "signature"
          - "x509-cert"
        update-types:
          - "major"
          - "minor"
          - "patch"
    ignore:
      - dependency-name: "signature"
        update-types:
          - "version-update:semver-major"
      - dependency-name: "der"
        update-types:
          - "version-update:semver-major"
