[workspace]
members = [
    "attestation-core",
    "backend",
    "certificate-core",
    "crl-core",
    "crypto-core",
    "daemon",
    "injector-core",
    "keybox-core",
    "native-core",
    "policy-config-core",
    "service-core",
    "webui-bridge",
    "xml-core"
]
resolver = "2"

[profile.release]
lto = "fat"
codegen-units = 1
strip = true
opt-level = "z"
panic = "unwind"